<?php
namespace app\api\command;
use think\console\Command;
use think\console\Input;
use think\console\Output;

/**
 * Created by PhpStorm.
 * User: root
 * Date: 2019/11/28
 * Time: 14:19
 */
class Access extends Command{

    /**
     * 定时获取access_token
     */
    protected function configure()
    {
        $this->setName('Access')->setDescription('定时获取access_token');

    }


    protected function execute(Input $input, Output $output)
    {
        $data=[
            'grant_type'=>'client_credential',
            'appid'=>config('setting.weixin.appid'),
            'secret'=>config('setting.weixin.AppSecret')
        ];
        $url =config('setting.weixin.url_token').http_build_query($data);
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }


}